"""Add new table : poll_group

Revision ID: 113c250468f2
Revises: b593a6a9b9ac
Create Date: 2026-06-09 19:25:16.460925

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '113c250468f2'
down_revision: Union[str, Sequence[str], None] = 'b593a6a9b9ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('poll_group',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.BigInteger(), nullable=False),
    sa.Column('is_public_result', sa.Boolean(), nullable=True),
    sa.Column('is_closed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('expire_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('allow_multiple_choice', sa.Boolean(), nullable=True),
    sa.Column('delete_after_hours', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_poll_group_expire_at'), 'poll_group', ['expire_at'], unique=False)
    op.create_index(op.f('ix_poll_group_is_closed'), 'poll_group', ['is_closed'], unique=False)
    op.create_index(op.f('ix_poll_group_owner_id'), 'poll_group', ['owner_id'], unique=False)
    op.add_column('polls', sa.Column('group_id', sa.UUID(), nullable=False))
    op.drop_index(op.f('ix_polls_expire_at'), table_name='polls')
    op.drop_index(op.f('ix_polls_is_closed'), table_name='polls')
    op.drop_index(op.f('ix_polls_owner_id'), table_name='polls')
    op.create_index(op.f('ix_polls_group_id'), 'polls', ['group_id'], unique=False)
    op.drop_constraint(op.f('polls_owner_id_fkey'), 'polls', type_='foreignkey')
    op.create_foreign_key(None, 'polls', 'poll_group', ['group_id'], ['id'], ondelete='CASCADE')
    op.drop_column('polls', 'is_public_result')
    op.drop_column('polls', 'expire_at')
    op.drop_column('polls', 'delete_after_hours')
    op.drop_column('polls', 'created_at')
    op.drop_column('polls', 'owner_id')
    op.drop_column('polls', 'allow_multiple_choice')
    op.drop_column('polls', 'is_closed')
    op.add_column('qr_tokens', sa.Column('poll_group_id', sa.UUID(), nullable=False))
    op.drop_index(op.f('ix_qr_tokens_poll_id'), table_name='qr_tokens')
    op.create_index(op.f('ix_qr_tokens_poll_group_id'), 'qr_tokens', ['poll_group_id'], unique=False)
    op.drop_constraint(op.f('qr_tokens_poll_id_fkey'), 'qr_tokens', type_='foreignkey')
    op.create_foreign_key(None, 'qr_tokens', 'poll_group', ['poll_group_id'], ['id'], ondelete='CASCADE')
    op.drop_column('qr_tokens', 'poll_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('qr_tokens', sa.Column('poll_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'qr_tokens', type_='foreignkey')
    op.create_foreign_key(op.f('qr_tokens_poll_id_fkey'), 'qr_tokens', 'polls', ['poll_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_qr_tokens_poll_group_id'), table_name='qr_tokens')
    op.create_index(op.f('ix_qr_tokens_poll_id'), 'qr_tokens', ['poll_id'], unique=False)
    op.drop_column('qr_tokens', 'poll_group_id')
    op.add_column('polls', sa.Column('is_closed', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('polls', sa.Column('allow_multiple_choice', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('polls', sa.Column('owner_id', sa.BIGINT(), autoincrement=False, nullable=False))
    op.add_column('polls', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False))
    op.add_column('polls', sa.Column('delete_after_hours', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('polls', sa.Column('expire_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('polls', sa.Column('is_public_result', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'polls', type_='foreignkey')
    op.create_foreign_key(op.f('polls_owner_id_fkey'), 'polls', 'users', ['owner_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_polls_group_id'), table_name='polls')
    op.create_index(op.f('ix_polls_owner_id'), 'polls', ['owner_id'], unique=False)
    op.create_index(op.f('ix_polls_is_closed'), 'polls', ['is_closed'], unique=False)
    op.create_index(op.f('ix_polls_expire_at'), 'polls', ['expire_at'], unique=False)
    op.drop_column('polls', 'group_id')
    op.drop_index(op.f('ix_poll_group_owner_id'), table_name='poll_group')
    op.drop_index(op.f('ix_poll_group_is_closed'), table_name='poll_group')
    op.drop_index(op.f('ix_poll_group_expire_at'), table_name='poll_group')
    op.drop_table('poll_group')
    # ### end Alembic commands ###
