"""revert

Revision ID: 36229430af65
Revises: 47a47f9ab99a
Create Date: 2026-06-15 11:05:07.300665

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36229430af65'
down_revision: Union[str, Sequence[str], None] = '47a47f9ab99a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('poll',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('group_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('allow_multiple_choice', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['poll_group.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_poll_group_id'), 'poll', ['group_id'], unique=False)
    op.add_column('poll_options', sa.Column('poll_id', sa.UUID(), nullable=False))
    op.create_index(op.f('ix_poll_options_poll_id'), 'poll_options', ['poll_id'], unique=False)
    op.create_foreign_key(None, 'poll_options', 'poll', ['poll_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'poll_options', type_='foreignkey')
    op.drop_index(op.f('ix_poll_options_poll_id'), table_name='poll_options')
    op.drop_column('poll_options', 'poll_id')
    op.drop_index(op.f('ix_poll_group_id'), table_name='poll')
    op.drop_table('poll')
    # ### end Alembic commands ###
