"""now poll_option contain poll_group_qr

Revision ID: 47a47f9ab99a
Revises: 
Create Date: 2026-06-15 10:28:24.038688

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47a47f9ab99a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'poll_group', ['qr_token'])
    op.add_column('poll_options', sa.Column('poll_group_qr', sa.String(length=255), nullable=False))
    op.drop_index(op.f('ix_poll_options_poll_id'), table_name='poll_options')
    op.drop_constraint(op.f('uq_poll_options_poll_order'), 'poll_options', type_='unique')
    op.create_index(op.f('ix_poll_options_poll_group_qr'), 'poll_options', ['poll_group_qr'], unique=False)
    op.create_unique_constraint(None, 'poll_options', ['id'])
    op.create_foreign_key(None, 'poll_options', 'poll_group', ['poll_group_qr'], ['qr_token'], ondelete='CASCADE')
    op.drop_column('poll_options', 'poll_id')
    op.add_column('votes', sa.Column('poll_group_qr', sa.String(length=255), nullable=False))
    op.drop_index(op.f('ix_votes_poll_id'), table_name='votes')
    op.drop_constraint(op.f('uq_votes_poll_anon_option'), 'votes', type_='unique')
    op.create_unique_constraint('uq_votes_poll_anon_option', 'votes', ['poll_group_qr', 'anonymous_id', 'option_id'])
    op.create_index(op.f('ix_votes_poll_group_qr'), 'votes', ['poll_group_qr'], unique=False)
    op.create_foreign_key(None, 'votes', 'poll_group', ['poll_group_qr'], ['qr_token'], ondelete='CASCADE')
    op.drop_column('votes', 'poll_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('votes', sa.Column('poll_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'votes', type_='foreignkey')
    op.drop_index(op.f('ix_votes_poll_group_qr'), table_name='votes')
    op.drop_constraint('uq_votes_poll_anon_option', 'votes', type_='unique')
    op.create_unique_constraint(op.f('uq_votes_poll_anon_option'), 'votes', ['poll_id', 'anonymous_id', 'option_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_votes_poll_id'), 'votes', ['poll_id'], unique=False)
    op.drop_column('votes', 'poll_group_qr')
    op.add_column('poll_options', sa.Column('poll_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'poll_options', type_='foreignkey')
    op.drop_constraint(None, 'poll_options', type_='unique')
    op.drop_index(op.f('ix_poll_options_poll_group_qr'), table_name='poll_options')
    op.create_unique_constraint(op.f('uq_poll_options_poll_order'), 'poll_options', ['poll_id', 'display_order'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_poll_options_poll_id'), 'poll_options', ['poll_id'], unique=False)
    op.drop_column('poll_options', 'poll_group_qr')
    op.drop_constraint(None, 'poll_group', type_='unique')
    # ### end Alembic commands ###
