"""Add new colum for pollgroup

Revision ID: 4f5a70afe855
Revises: ce1fb5f1e976
Create Date: 2026-06-10 09:33:48.530939

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f5a70afe855'
down_revision: Union[str, Sequence[str], None] = 'ce1fb5f1e976'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('poll_group', sa.Column('title', sa.String(length=255), nullable=False))
    op.add_column('poll_group', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('poll_group', 'description')
    op.drop_column('poll_group', 'title')
    # ### end Alembic commands ###
