"""Move miltiple choice to Polls where befor poll group

Revision ID: 7a0daf29b41c
Revises: 4f5a70afe855
Create Date: 2026-06-10 09:48:14.527891

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a0daf29b41c'
down_revision: Union[str, Sequence[str], None] = '4f5a70afe855'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('poll_group', 'allow_multiple_choice')
    op.add_column('polls', sa.Column('allow_multiple_choice', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('polls', 'allow_multiple_choice')
    op.add_column('poll_group', sa.Column('allow_multiple_choice', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
