"""vote table change

Revision ID: aff56d16c962
Revises: 051b595f8b2c
Create Date: 2026-06-01 13:55:46.027904

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aff56d16c962'
down_revision: Union[str, Sequence[str], None] = '051b595f8b2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_votes_poll_anon'), 'votes', type_='unique')
    op.create_unique_constraint('uq_votes_poll_anon_option', 'votes', ['poll_id', 'anonymous_id', 'option_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_votes_poll_anon_option', 'votes', type_='unique')
    op.create_unique_constraint(op.f('uq_votes_poll_anon'), 'votes', ['poll_id', 'anonymous_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
