"""initial

Revision ID: d6a221e4a9c6
Revises: 
Create Date: 2026-06-18 09:53:08.775757

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6a221e4a9c6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('login_id', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('expire_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_expire_at'), 'users', ['expire_at'], unique=False)
    op.create_index(op.f('ix_users_login_id'), 'users', ['login_id'], unique=True)
    op.create_table('poll_group',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('owner_id', sa.BigInteger(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('qr_token', sa.String(length=255), nullable=False),
    sa.Column('is_public_result', sa.Boolean(), nullable=True),
    sa.Column('is_closed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('expire_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('delete_after_hours', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('qr_token')
    )
    op.create_index(op.f('ix_poll_group_expire_at'), 'poll_group', ['expire_at'], unique=False)
    op.create_index(op.f('ix_poll_group_is_closed'), 'poll_group', ['is_closed'], unique=False)
    op.create_index(op.f('ix_poll_group_owner_id'), 'poll_group', ['owner_id'], unique=False)
    op.create_table('poll',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('group_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('allow_multiple_choice', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['poll_group.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_poll_group_id'), 'poll', ['group_id'], unique=False)
    op.create_table('poll_options',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('poll_id', sa.UUID(), nullable=False),
    sa.Column('poll_group_qr', sa.String(length=255), nullable=False),
    sa.Column('option_text', sa.String(length=255), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['poll_group_qr'], ['poll_group.qr_token'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['poll_id'], ['poll.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_poll_options_poll_group_qr'), 'poll_options', ['poll_group_qr'], unique=False)
    op.create_index(op.f('ix_poll_options_poll_id'), 'poll_options', ['poll_id'], unique=False)
    op.create_table('votes',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('poll_group_qr', sa.String(length=255), nullable=False),
    sa.Column('option_id', sa.BigInteger(), nullable=False),
    sa.Column('anonymous_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['option_id'], ['poll_options.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['poll_group_qr'], ['poll_group.qr_token'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('poll_group_qr', 'anonymous_id', 'option_id', name='uq_votes_poll_anon_option')
    )
    op.create_index(op.f('ix_votes_anonymous_id'), 'votes', ['anonymous_id'], unique=False)
    op.create_index(op.f('ix_votes_option_id'), 'votes', ['option_id'], unique=False)
    op.create_index(op.f('ix_votes_poll_group_qr'), 'votes', ['poll_group_qr'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_votes_poll_group_qr'), table_name='votes')
    op.drop_index(op.f('ix_votes_option_id'), table_name='votes')
    op.drop_index(op.f('ix_votes_anonymous_id'), table_name='votes')
    op.drop_table('votes')
    op.drop_index(op.f('ix_poll_options_poll_id'), table_name='poll_options')
    op.drop_index(op.f('ix_poll_options_poll_group_qr'), table_name='poll_options')
    op.drop_table('poll_options')
    op.drop_index(op.f('ix_poll_group_id'), table_name='poll')
    op.drop_table('poll')
    op.drop_index(op.f('ix_poll_group_owner_id'), table_name='poll_group')
    op.drop_index(op.f('ix_poll_group_is_closed'), table_name='poll_group')
    op.drop_index(op.f('ix_poll_group_expire_at'), table_name='poll_group')
    op.drop_table('poll_group')
    op.drop_index(op.f('ix_users_login_id'), table_name='users')
    op.drop_index(op.f('ix_users_expire_at'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
